const $=s=>document.querySelector(s);const modes=["AMRAP","FOR TIME","EMOM","INTERVAL","TABATA"];
let mode="INTERVAL",settings={name:"Mon workout",work:40,rest:20,rounds:10,prep:10,duration:600,cap:600},workouts=[],timer=null,state=null,sound=true,audioCtx=null,deferredPrompt=null;
try{workouts=JSON.parse(localStorage.getItem("wt_workouts")||"[]")}catch{}if(!workouts.length){workouts=[{id:1,name:"10 × 40/20",mode:"INTERVAL",work:40,rest:20,rounds:10,prep:10},{id:2,name:"Tabata classique",mode:"TABATA",work:20,rest:10,rounds:8,prep:10}];saveWorkouts()}
function saveWorkouts(){localStorage.setItem("wt_workouts",JSON.stringify(workouts))}function fmt(s){s=Math.max(0,Math.ceil(s));return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}function fmt1(s){s=Math.max(0,Math.floor(s));return`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function beep(freq=700,d=.08){if(!sound)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.12;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}function vib(p=35){navigator.vibrate?.(p)}function speak(t){if(!sound||!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=1.1;speechSynthesis.speak(u)}function unlock(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}}
function renderModes(){$("#modeGrid").innerHTML=modes.map(m=>`<button class="mode-btn ${m===mode?"active":""}" data-mode="${m}">${m}</button>`).join("");document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderModes();renderSettings()})}
function row(label,k,step,min,max,help){return`<div class="setting-row"><div><div class="setting-label">${label}</div><div class="setting-help">${help}</div></div><div class="stepper"><button data-k="${k}" data-d="-1">−</button><div class="value">${k==="rounds"?settings[k]:fmt(settings[k])}</div><button data-k="${k}" data-d="1">+</button></div></div>`}
function renderSettings(){let h=`<div class="setting-row"><div style="width:100%"><div class="setting-label">Nom</div><input id="nameInput" class="text-input" maxlength="40" value="${esc(settings.name)}"></div></div>`;
if(mode==="AMRAP")h+=row("Durée","duration",30,30,3600,"Travail libre pendant cette durée");else if(mode==="FOR TIME")h+=row("Time cap","cap",30,30,3600,"Temps maximum");else h+=row(mode==="EMOM"?"Intervalle":"Work","work",5,5,3600,"Temps d'effort");
if(["INTERVAL","TABATA"].includes(mode))h+=row("Rest","rest",5,0,3600,"Récupération");if(!["AMRAP","FOR TIME"].includes(mode))h+=row("Rounds","rounds",1,1,999,"Nombre de tours");h+=row("Get ready","prep",5,0,60,"Préparation");
$("#settingsCard").innerHTML=h;$("#nameInput").oninput=e=>settings.name=e.target.value;document.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{let k=b.dataset.k,d=+b.dataset.d,step=k==="rounds"?1:k==="prep"?5:k==="duration"||k==="cap"?30:5,min=k==="rounds"?1:k==="prep"?0:0,max=k==="rounds"?999:k==="prep"?60:3600;settings[k]=Math.min(max,Math.max(min,settings[k]+d*step));renderSettings()})}
function meta(w){if(w.mode==="AMRAP")return fmt(w.duration);if(w.mode==="FOR TIME")return`cap ${fmt(w.cap)}`;return w.mode==="EMOM"?`${fmt(w.work)} × ${w.rounds}`:`${fmt(w.work)}/${fmt(w.rest)} × ${w.rounds}`}
function renderSaved(){$("#savedList").innerHTML=workouts.map(w=>`<div class="saved-card"><div><div class="saved-name">${esc(w.name)}</div><div class="saved-meta">${w.mode} · ${meta(w)}</div></div><div class="saved-actions"><button data-load="${w.id}">OUVRIR</button><button data-del="${w.id}">✕</button></div></div>`).join("");document.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{let w=workouts.find(x=>x.id==b.dataset.load);mode=w.mode;settings={...settings,...w};renderModes();renderSettings()});document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{workouts=workouts.filter(x=>x.id!=b.dataset.del);saveWorkouts();renderSaved()})}
function show(id){["setup","timer","done"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id))}
function saveCurrent(){let w={id:Date.now(),...settings,mode};workouts=[w,...workouts.filter(x=>x.name!==w.name)].slice(0,30);saveWorkouts();renderSaved()}
function start(){unlock();saveCurrent();state={phase:"PREP",round:1,remaining:settings.prep,elapsed:0,last:performance.now(),paused:false};$("#timerTitle").textContent=(settings.name||"WORKOUT").toUpperCase();$("#finishBtn").classList.toggle("hidden",!["AMRAP","FOR TIME"].includes(mode));show("timer");render();clearInterval(timer);timer=setInterval(tick,50);if(!settings.prep)begin();else speak("Get ready")}
function begin(){state.phase="WORK";state.remaining=mode==="AMRAP"?settings.duration:mode==="EMOM"?settings.work:settings.work;speak("Go");beep(900,.1);vib(40);render()}
function tick(){if(!state||state.paused)return;let n=performance.now(),dt=(n-state.last)/1000;state.last=n;if(state.phase==="PREP")state.remaining-=dt;else{state.elapsed+=dt;if(mode!=="FOR TIME")state.remaining-=dt;if(mode==="FOR TIME"&&settings.cap>0&&state.elapsed>=settings.cap)return finish();}if(state.phase==="PREP"&&state.remaining<=0)begin();else if(state.phase==="WORK"&&mode!=="FOR TIME"&&state.remaining<=0)advance();render()}
function advance(){if(mode==="AMRAP")return finish();if(mode==="EMOM"){if(state.round>=settings.rounds)return finish();state.round++;state.remaining=settings.work;speak(`Round ${state.round}`);beep(900,.08);vib(40);return}if(state.phase==="WORK"&&settings.rest>0){state.phase="REST";state.remaining=settings.rest;speak("Rest");beep(600,.1);vib(40);return}if(state.round>=settings.rounds)return finish();state.round++;state.phase="WORK";state.remaining=settings.work;speak(`Round ${state.round}, work`);beep(900,.08);vib(40)}
function render(){if(!state)return;$("#prepLabel").classList.toggle("hidden",state.phase!=="PREP");$("#phaseLabel").classList.toggle("hidden",state.phase==="PREP");$("#phaseLabel").textContent=state.phase==="REST"?"REST":"WORK";$("#timeDisplay").textContent=mode==="FOR TIME"&&state.phase!=="PREP"?fmt1(state.elapsed):fmt(state.remaining);$("#roundDisplay").textContent=mode==="AMRAP"||mode==="FOR TIME"?"":`ROUND ${state.round} / ${settings.rounds}`;$("#totalDisplay").textContent=mode==="FOR TIME"?"":`TOTAL ${fmt1(state.elapsed)}`;$("#pauseBtn").textContent=state.paused?"▶":"Ⅱ";let max=state.phase==="REST"?settings.rest:settings.work;$("#progressBar").style.width=state.phase==="PREP"||mode==="FOR TIME"?"0%":`${Math.max(0,Math.min(100,100*(1-state.remaining/max)))}%`}
function finish(){clearInterval(timer);timer=null;$("#doneTitle").textContent=settings.name||"Workout terminé";$("#doneTime").textContent=fmt1(state.elapsed);show("done");speak("Workout complete");beep(1000,.12);vib([60,50,120])}
$("#startBtn").onclick=start;$("#newWorkoutBtn").onclick=()=>{mode="INTERVAL";settings={name:"Nouveau workout",work:40,rest:20,rounds:10,prep:10,duration:600,cap:600};renderModes();renderSettings()};$("#pauseBtn").onclick=()=>{state.paused=!state.paused;state.last=performance.now();render()};$("#skipBtn").onclick=()=>{if(state?.phase!=="PREP")advance()};$("#finishBtn").onclick=finish;$("#exitBtn").onclick=()=>{clearInterval(timer);state=null;show("setup")};$("#doneBackBtn").onclick=()=>{state=null;show("setup");renderSaved()};$("#soundBtn").onclick=()=>{sound=!sound;$("#soundBtn").textContent=sound?"🔊":"🔇";if(sound)unlock()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").classList.add("hidden")}};
document.addEventListener("visibilitychange",()=>{if(state&&!state.paused)state.last=performance.now()});if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});renderModes();renderSettings();renderSaved();